export const clubdata = [
  {
    no: "one",
    name: "AUV",
    mail: "auv.society@iiitdm.ac.in",
    r1: "Muthu Shravan",
    ramail: "me20b1009@iiitdm.ac.in",
    rapno: "9176677701",
    r2: "Venkata Madhav",
    rbmail: "cs20b1047@iiitdm.ac.in",
    rbpno: "99665 41718",
    pic: "Dr. Karthik.C",
    picname: "Dr. Karthik.C",
    picmail: "karthikc@iiitdm.ac.in",
    picpno: "",
    website: "https://auviiitdm.github.io/",
    type: "row",
    background: "linear-gradient(to left, #e3e9e7 60%, #6998ab)",
    raimage: "/assests/images/clubRep/auv_1.png",
    rbimage: "/assests/images/clubRep/auv_2.png",
    picimage: "/assests/images/pic/auv_pic.jpeg",
    desc: "We are a team of 9 interdisciplinary undergraduate engineers working to build an autonomous underwater vehicle for various underwater robotics competitions. The team works in robotic domains of mechanical, electronics, and software. We want to bind together our theoretical knowledge and put it into an underwater vehicle that can go and explore the vast seas.",
    cimage1: "/assests/images/clubImages/auv_1.png",
    cimage2: "/assests/images/clubImages/auv_2.png",
    cimage3: "/assests/images/clubImages/auv_3.png",
    logo: "/assests/images/clubLogos/auv.png",
    pic2: "",
    pic2name: "",
    pic2image: "",
    pic2mail: "",
    pic2pno: "",
    linkedin: "https://www.linkedin.com/company/auv-iiitdm-kancheepuram/",
    instagram: "https://www.instagram.com/auv_iiitdm/",
    discord: "https://discord.com/invite/3sxM6fhbWM",
  },
  {
    no: "two",
    picname: "Dr. Masilamani V",
    picmail: "masila@iiitdm.ac.in",
    picpno: "",
    name: "CS",
    mail: "csclub@iiitdm.ac.in",
    r1: "Kadlag Atharva Sanjay",
    ramail: "ced19i015@iiitdm.ac.in",
    rapno: "7620763769",
    pic: "Dr.Masilamani V",
    website: "https://csclub.netlify.app/",
    type: "row-reverse",
    background: "linear-gradient(to left, #e3e9e7 60%, #6998ab)",
    desc: "Here at the CS Club, we act as a gateway for students to enter the Computer Science Community and Industry. We strive to educate, train, and guide students as they build towards a profession in CS Industry. We aren't just a club, we're an independent body where students learn together, help each other sharpen their skills and create their future in the industry. We help students passionate in the field of Computer Science by providing lectures and activities on the newest branches of Computer Science, training them in the exciting sport of competitive programming. Introducing students to the Computer Science Industry by hosting Industrial Talks and Research Projects",
    raimage: "",
    rbimage: "",
    picimage: "/assests/images/pic/cs_pic.jpg",
    cimage1: "",
    cimage2: "",
    cimage3: "",
    logo: "/assests/images/clubLogos/csclub.jpg",
    pic2: "",
    pic2name: "",
    pic2image: "",
    pic2mail: "",
    pic2pno: "",
    linkedin:
      "https://www.google.com/url?q=https://www.linkedin.com/company/cs-club-iiitdm-kancheepuram/&sa=D&source=editors&ust=1667199486778219&usg=AOvVaw3v_pDxiUvOuYRcNnAbN0Q-",
    instagram:
      "https://www.google.com/url?q=https://www.instagram.com/cs.club.iiitdm/?hl%3Den&sa=D&source=editors&ust=1667199486777558&usg=AOvVaw10MzngGdmSwhsnXNvi2tNg",
    discord: "https://discord.com/invite/Ewk4YvyREt",
  },
  {
    no: "three",
    picname: "picname",
    picmail: "picmail",
    picpno: "picpno",
    name: "EDC",
    mail: "edc@iiitdm.ac.in",
    r1: "Abhishek",
    ramail: "evd19i004@iiitdm.ac.in",
    rapno: "9566034502",
    r2: "Aswathy Manoj Kumar",
    rbmail: "evd19i028@iiitdm.ac.in",
    rbpno: "7356393699",
    pic: "Pic",
    website: "/clubs",
    type: "row",
    background: "linear-gradient(to left, #e3e9e7 60%, #6998ab)",
    desc: "The club organises interesting sessions on circuit synthesis, Arduino programming and electronics software. The club encourages student projects and helps them source ideas and components as well.The purpose of this club is to provide access and help in research in the areas relating to electronics with hands-on knowledge and experience. The club aims to achieve those mentioned above by conducting industrial talks, open engineering discussion forums, and collaborating with clubs within and from other institutions.",
    raimage: "",
    rbimage: "",
    picimage: "",
    logo: "/assests/images/clubLogos/edc.jpg",
    pic2: "",
    pic2name: "",
    pic2image: "",
    pic2mail: "",
    pic2pno: "",
    linkedin: "",
    instagram: "https://www.instagram.com/edc_iiitdm/",
    discord: "",
  },
  {
    no: "four",
    picname: "Dr. Sudhir Varadarajan",
    picmail: "sudhir@iiitdm.ac.in",
    picpno: "+91-44-27476366",
    name: "EPiC",
    mail: "epic@iiitdm.ac.in",
    r1: "Habel Saju",
    ramail: "cs20b1037@iiitdm.ac.in",
    rapno: "7560942841",
    r2: "Sriram Kanakam",
    rbmail: "ec20b1060@iiitdm.ac.in",
    rbpno: "8790139405",
    pic: "Dr. Sudhir V",
    website: "/clubs",
    type: "row-reverse",
    background: "linear-gradient(to right, #e3e9e7 60%, #6998ab)",
    raimage: "",
    rbimage: "",
    picimage: "/assests/images/pic/epic_pic.jpg",
    logo: "/assests/images/clubLogos/EPiC.jpg",
    desc: "The Entrepreneurship and Investment Club (EPIC), lends a helping hand to shape your dream into a commercial reality. The aim is to provide the necessary platform for the students with the ambition and determination to pursue the life long journey of becoming an entrepreneur. EPIC encourages ingenious thinking and provokes students to generate novel ideas making it truly the “centre” for innovation in the commercial sector.",
    pic2: "",
    pic2name: "",
    pic2image: "",
    pic2mail: "",
    pic2pno: "",
    linkedin: "https://www.linkedin.com/company/epic-iiitdm",
    instagram: "https://www.instagram.com/epic_iiitdm/",
    discord: "https://discord.com/invite/XnEZAb4F9t",
  },
  {
    no: "five",
    picname: "Dr. Ram Prasad Padhy",
    picmail: "rampadhy@iiitdm.ac.in",
    picpno: "",
    name: "GDSC",
    mail: "gdsc@iiitdm.ac.in",
    r1: "Aryaman Gadia",
    ramail: "ced19i055@iitdm.ac.in",
    rapno: "6205711441",
    pic: "Dr. Ram Prasad",
    website:
      "https://gdsc.community.dev/indian-institute-of-information-technology-design-manufacturing-kancheepuram/",
    type: "row",
    background: "linear-gradient(to left, #e3e9e7 60%, #6998ab)",
    raimage: "",
    rbimage: "",
    picimage: "/assests/images/pic/GDSC_pic.jpg",
    logo: "/assests/images/clubLogos/gdsc.png",
    desc: "“Google Developer Student Clubs are university based community groups for students interested in Google developer technologies. Students from all undergraduate or graduate programs with an interest in growing as a developer are welcome. By joining a GDSC, students grow their knowledge in a peer-to-peer learning environment and build solutions for local businesses and their community.”",
    pic2: "",
    pic2name: "",
    pic2image: "",
    pic2mail: "",
    pic2pno: "",
    linkedin: "",
    instagram: "",
    discord: "",
  },
  {
    no: "six",
    picname: "Mr. S. Sundara Mohan",
    picmail: "sundaramohan@iiitdm.ac.in",
    picpno: "",
    name: "IDC",
    mail: "idc@iiitdm.ac.in",
    r1: "Ram Guguloth",
    ramail: "mdm19b029@iiitdm.ac.in",
    rapno: "9666351636",
    pic: "Mr.S.Sundara Mohan",
    website: "/clubs",
    type: "row-reverse",
    background: "linear-gradient(to left, #e3e9e7 60%, #6998ab)",
    raimage: "/assests/images/clubRep/IDC_1.png",
    rbimage: "",
    picimage: "/assests/images/pic/IDC_pic.png",
    logo: "/assests/images/clubLogos/idc.png",
    desc: "Industrial Design (ID) is the professional practice of designing products, devices, objects, and services used by millions of people around the world every day.The Industrial Design Club (IDC) creates an ecosystem for students from all departments to learn and discuss Industrial Design principles and practices.The primary goal of this club is to introduce the industrial design field by practicing various design-related skills, including sketching, 3D modeling, design thinking, prototyping, etc.",
    pic2: "",
    pic2name: "",
    pic2image: "",
    pic2mail: "",
    pic2pno: "",
    linkedin: "",
    instagram: "https://www.instagram.com/innovate_iiitdm/",
    discord: "https://discord.com/invite/dDGjaHxRaA",
  },
  {
    no: "seven",
    picname: "Dr. Shubhankar Chakraborty",
    picmail: "shubhankar@iiitdm.ac.in",
    picpno: "04427476370",
    name: "MARS",
    mail: "mars@iiitdm.ac.in",
    r1: "Radhika Mittal",
    ramail: "ced19i050@iiitdm.ac.in",
    rapno: "9150993173",
    r2: "Vishnu Kumar",
    rbmail: "me20b2001@iiitdm.ac.in",
    rbpno: "9672021848",
    pic: "Dr.Shubhankar Chakraborty",
    website: "https://marsroversociety.netlify.app/",
    type: "row",
    background: "linear-gradient(to right, #e3e9e7 60%, #6998ab)",
    raimage: "",
    rbimage: "",
    picimage: "/assests/images/pic/mars_pic.jpg",
    cimage1: "/assests/images/clubImages/mars_1.png",
    cimage2: "/assests/images/clubImages/mars_2.png",
    cimage3: "/assests/images/clubImages/mars_3.png",
    logo: "/assests/images/clubLogos/mars.png",
    desc: "Mars Research Station, formerly known as MRC, had been set up by a group of students from IIITDM Kancheepuram, which aims to compete at international competitions on building advanced space systems.    This team mainly focuses on participating in Indian Rover Challenge (IRC), European Rover Challenge (ERC), Australian Rover Challenge(ARC) and University Rover Challenge (URC). To do so people from different backgrounds come together and work as a team to build a system according to the problem statement for these competitions.Here we aim to build remotely operated rovers that can accomplish a variety of tasks that might one day assist astronauts working on the surface of Mars. ",
    pic2: "",
    pic2name: "",
    pic2image: "",
    pic2mail: "",
    pic2pno: "",
    linkedin: "https://www.linkedin.com/company/mars-rover-society",
    instagram: "https://www.instagram.com/mars_iiitdm/",
    discord: "",
  },
  {
    no: "eight",
    picname: "Dr.Srijith.K",
    picmail: "srijith@iiitdm.ac.in",
    picpno: "+914427476337",
    name: "Optica",
    mail: "optica@iiitdm.ac.in",
    r1: "Sharath Devanand",
    ramail: "edm19b051@iiitdm.ac.in",
    rapno: "9390094481",
    r2: "",
    rbmail: "edm19b039@iiitdm.ac.in",
    rbpno: "8688923237",
    pic: "Dr.Srijith.K",
    website: "/clubs",
    type: "row-reverse",
    background: "linear-gradient(to right, #e3e9e7 60%, #6998ab)",
    raimage: "",
    rbimage: "",
    picimage: "/assests/images/pic/optica_pic.jpg",
    logo: "/assests/images/clubLogos/optica.jpg",
    desc: "OPTICA's (formerly known as OSA) mission is to promote the generation, application, and archiving of knowledge in optics and photonics and to disseminate this knowledge worldwide.",
    pic2: "",
    pic2name: "",
    pic2image: "",
    pic2mail: "",
    pic2pno: "",
    linkedin: "",
    instagram: "https://www.instagram.com/iiitdm_optica/?utm_medium=copy_link",
    discord: "",
  },
  {
    no: "nine",
    picname: "picname",
    picmail: "picmail",
    picpno: "picpno",
    name: "Robotics",
    mail: "robotics@iiitdm.ac.in",
    r1: "Utkarsh Verma",
    ramail: "edm19b038@iiitdm.ac.in",
    rapno: "6393832334",
    pic: "Pic",
    website: "https://sites.google.com/view/roboticsclub-iiitdm/home",
    type: "row",
    background: "linear-gradient(to right, #e3e9e7 60%, #6998ab)",
    raimage: "",
    rbimage: "",
    picimage: "",
    logo: "/assests/images/clubLogos/roboticsclub.png",
    desc: "Robotics plays a major role in making our day to day life easier. It unifies various branches of engineering and also symbolises the importance of one branch in the other. This promotes hands-on and cooperative learning and also engages students in problem-solving and higher-order thinking. People taking part in the sessions with dedication get exposure to many other areas apart from their syllabus.The organization is centered around a platform for members and non-member students with a passion for robotics to come together and develop projects in the domain of robotics and to also act as a channel for various students to come together to participate in multiple robotics-based competitions.  “Inspire, Introduce, Initiate” is the mantra of the club. ",
    pic2: "",
    pic2name: "",
    pic2image: "",
    pic2mail: "",
    pic2pno: "",
    linkedin: "",
    instagram: "https://www.instagram.com/roboticsclub.iiitdm/",
    discord: "https://discord.com/invite/SXesFHkW5u",
  },
  {
    name: "SAE",
    mail: "saeclub@iiitdm.ac.in",
    r1: "K Mithelesh",
    ramail: "mpd18i008@iiitdm.ac.in",
    rapno: "9176677701",
    r2: "Abaethan S",
    rbmail: "mdm19b015@iiitdm.ac.in",
    rbpno: "8778853602",
    website: "https://infinitechallenger.in/",
    type: "row-reverse",
    background: "linear-gradient(to right, #e3e9e7 60%, #6998ab)",
    no: "ten",
    picname: "Dr.Kashfull Orra",
    picmail: "orra@iiitdm.ac.in",
    picpno: "+914427476121",
    pic: "Dr.Kashfull Orra",
    raimage: "/assests/images/clubRep/sae_1.png",
    rbimage: "/assests/images/clubRep/sae_2.png",
    picimage: "/assests/images/pic/sae_pic.jpg",
    logo: "/assests/images/clubLogos/sae.jpg",
    desc: "The purpose of this organisation is to provide its members opportunities to gain broader insight into the engineering profession by sponsoring meetings that will bring practising engineers to the campus, arranging field trips to research and engineering establishments, sponsoring student projects of engineering interest, and participating in SAEINDIA Section activities to hold up the values instilled by the institution.",
    pic2: "Dr.Shubhankar Chakraborty",
    pic2name: "Dr.Shubhankar Chakraborty",
    pic2image: "/assests/images/pic/mars_pic.jpg",
    pic2mail: "shubhankar@iiitdm.ac.in",
    pic2pno: "04427476370",
    linkedin: "https://www.linkedin.com/company/sae-iiitdm-kancheepuram",
    instagram: "https://www.instagram.com/sae_iiitdm/",
    discord: "https://discord.com/invite/7KDTJfeYha",
  },
];
