export const Facultydetails = [
  {
    name: "Dr Sudhir Varadarajan",
    phone: "+91-44-27476366",
    email: "sudhir@iiitdm.ac.in",
    position: "Faculty Advisor - EPIC",
    image: "sudhir.jpg",
    rollnumber: " ",
  },
  {
    name: "Dr. Masilamani V",
    phone: "+91-44-27476346",
    email: "masila@iiitdm.ac.in ",
    position: "Faculty Advisor - CS Club",
    image: "Masilamani.jpg",
    rollnumber: " ",
  },
  {
    name: "Dr. Srijith. K",
    phone: "+91 44 2747 6337",
    email: "srijith@iiitdm.ac.in",
    position: "Faculty Advisor - OSA",
    image: "srijith.jpg",
    rollnumber: " ",
  },
  {
    name: "Dr.Kashfull Orra",
    phone: "+91 44 2747 6121",
    email: "orra@iiitdm.ac.in",
    position: "Co-Faculty Advisor - SAE",
    image: "kashfull.jpg",
    rollnumber: " ",
  },
  {
    name: "Dr.Karthik C",
    phone: " ",
    email: "karthikc@iiitdm.ac.in",
    position: "Faculty Advisor - AUV",
    image: "karthik.jpg",
    rollnumber: " ",
  },
  {
    name: "Dr. Ram Prasad Padhy",
    phone: " ",
    email: "rampadhy@iiitdm.ac.in",
    position: "Faculty Advisor - GDSC",
    image: "rampadhy.jpg",
    rollnumber: " ",
  },
  {
    name: "FeliceSawtelle",
    phone: " ",
    email: "Cyb.Melan@gmail.com",
    position: "Dede",
    image: "test.jpg",
  },
];
export const Picsdetails = [
  {
    name: "Dr.Parvathy Das",
    phone: " ",
    email: "parvathydas@iiitdm.ac.in ",
    position: "PIC Extracurricular activites and Government Pragma",
    image: "parvathy.jpg",
    rollnumber: " ",
  },
  {
    name: "Dr.B.Sivaselvan",
    phone: "+91-44-27476343",
    email: "sivaselvanb@iiitdm.ac.in",
    position: "Dean Student affairs",
    image: "sivaselvan.jpg",
    rollnumber: " ",
  },
  {
    name: "Dr. Jayachandra Bingi",
    phone: "044-27476381",
    email: "bingi@iiitdm.ac.in",
    position: "PIC Designer club",
    image: "boy.jpg",
    rollnumber: " ",
  },
  {
    name: "Dr. Shubhankar Chakraborty",
    phone: "04427476370",
    email: "shubhankar@iiitdm.ac.in",
    position: "PIC SAE & Mars Club",
    image: "test.jpg",
    rollnumber: " ",
  },
  {
    name: "Dr.B.Chitti Babu",
    phone: "044-2747- 6377",
    email: "bcbabu@iiitdm.ac.in ",
    position: "PIC IEEE Student Branch",
    image: "test.jpg",
    rollnumber: " ",
  },
];
export const Pocdetails = [
  {
    name: "KARTHIKEYAN.S",
    phone: "8792385815",
    email: "ec21b1090@iiitdm.ac.in",
    position: "Public Outreach Committee - Co Lead",
    image: "karthikeyan.png",
    rollnumber: "EC21B1090",
  },
  {
    name: "SRINITHI N S",
    phone: "9487426964",
    email: "cs21b2044@iiitdm.ac.in",
    position: "Public Outreach Committee",
    image: "test.jpg",
    rollnumber: "CS21B2044",
  },
  {
    name: "Sakthiprian S",
    phone: "9791022154",
    email: "ec21b1075@iiitdm.ac.in",
    position: "Public Outreach Committee",
    image: "sakti.png",
    rollnumber: "EC21B1075",
  },

  {
    name: "K Jai Krishna",
    phone: "9789998350",
    email: "cs21b1088@iiitdm.ac.in",
    position: "Public Outreach Committee",
    image: "JaiKrishna.jpg",
    rollnumber: "CS21B1088",
  },

  {
    name: "ROHIT GUPTA",
    phone: "7320852074",
    email: "me21b1055@iiitdm.ac.in",
    position: "Public Outreach Committee",
    image: "test.jpg",
    rollnumber: "	ME21B1055",
  },
  {
    name: "Mrudula",
    phone: "7320852074",
    email: "me21b1055@iiitdm.ac.in",
    position: "Public Outreach Committee",
    image: "Mrudula.png",
    rollnumber: "	ME21B1055",
  },
  {
    name: "Videsh",
    phone: "7320852074",
    email: "me21b1055@iiitdm.ac.in",
    position: "Public Outreach Committee",
    image: "videsh.png",
    rollnumber: "	ME21B1055",
  },
];
export const Rmcdetails = [
  {
    name: "P KISHORE",
    Year: 2019,
    rollnumber: "EVD19I007",
    phone: 8197714735,
    email: "evd19i007@iiitdm.ac.in",
    position: "Resource Management Committee - Lead",
    image: "Kishore.jpg",
  },
  {
    name: "Jayanthaan Haribaskar",
    Year: 2019,
    rollnumber: "MDM19B010",
    phone: 8056414751,
    email: "mdm19b010@iiitdm.ac.in",
    position: "Resource Management Committee - Co Lead",
    image: "jayanthan.jpg",
  },
  {
    name: "Manas Narayan",
    Year: 2021,
    rollnumber: "EC21B1006",
    phone: 8853061366,
    email: "ec21b1006@iiitdm.ac.in",
    position: "Resource Management Committee",
    image: "manas.png",
  },
  {
    name: "Ananya Lakshmi Ravi",
    Year: 2021,
    rollnumber: "EC21B1004",
    phone: 9172194182,
    email: "ec21b1004@iiitdm.ac.in",
    position: "Resource Management Committee",
    image: "Ananya_Ravi.jpg",
  },
  {
    name: "Sundar Subramanian S",
    Year: 2021,
    rollnumber: "ME21B1059",
    phone: 6205746793,
    email: "me21b1059@iiitdm.ac.in",
    position: "Resource Management Committee",
    image: "test.jpg",
  },
];
export const Pmcdetails = [
  {
    name: "Shubham Gannamraju",
    phone: "7028724111",
    email: "coe19b037@iiitdm.ac.in",
    position: "Project Management Committee - Lead",
    image: "test.jpg",
    rollnumber: "COE19B037",
  },
  {
    name: "Yalamanchili Varshitha",
    Year: 2020,
    rollnumber: "Ec20b1118",
    phone: 9100292839,
    email: "ec20b1118@iiitdm.ac.in",
    position: "Project Management Committee - Co Lead",
    image: "varshitha.png",
  },
  {
    name: "Harsha Vasireddy",
    Year: 2020,
    rollnumber: "CS20B1033",
    phone: 9642287347,
    email: "cs20b1033@iiitdm.ac.in",
    position: "Project Management Committee - Co Lead",
    image: "Harsha.png",
  },
  {
    name: "A Vinay Kishore",
    Year: 2020,
    rollnumber: "cs20b1032",
    phone: 8309999640,
    email: "cs20b1032@iiitdm.ac.in",
    position: "Project Management Committee",
    image: "vinay.jpg",
  },
  {
    name: "Vishal A S",
    Year: 2021,
    rollnumber: "ME21B1048",
    phone: 9629086758,
    email: "me21b1048@iiitdm.ac.in",
    position: "Project Management Committee",
    image: "vishal.png",
  },
  {
    name: "Sibi M",
    Year: 2021,
    rollnumber: "Ec21b1042",
    phone: 9360455144,
    email: "ec21b1042@iiitdm.ac.in",
    position: "Project Management Committee",
    image: "Sibi.jpg",
  },
  {
    name: "KEERTHANA SRI S G",
    Year: 2021,
    rollnumber: "ME21B1046",
    phone: 9500168697,
    email: "me21b1046@iiitdm.ac.in",
    position: "Project Management Committee",
    image: "test.jpg",
  },
  {
    name: "KARTHIKEYAN.S",
    Year: 2021,
    rollnumber: "EC21B1090",
    phone: 8792385815,
    email: "ec21b1090@iiitdm.ac.in",
    position: "Public Outreach Committee",
    image: "test.jpg",
  },
  {
    name: "SRINITHI N S",
    Year: 2021,
    rollnumber: "CS21B2044",
    phone: 9487426964,
    email: "cs21b2044@iiitdm.ac.in",
    position: "Public Outreach Committee",
    image: "test.jpg",
  },
];
export const Teamsdetails = [
  {
    name: "Sukesh J R",
    Year: 2019,
    rollnumber: "MDM19B024",
    phone: 9894317341,
    email: "mdm19b024@iiitdm.ac.in",
    position: "Technical Affairs Secretary",
    image: "secretary.jpg",
  },
  {
    name: "Praneeth Kumar G",
    Year: 2020,
    rollnumber: "CS20B1130",
    phone: 9393107783,
    email: "cs20b1130@iiitdm.ac.in",
    position: "Technical Affairs Joint Secretary",
    image: "joint_sec.jpg",
  },
];
export const Sponsorshipdetails = [
  {
    name: "Ankit Kumar",
    Year: 2021,
    rollnumber: "ME21B1059",
    phone: 6205746793,
    email: "me21b1059@iiitdm.ac.in",
    position: "Sponsorship Committee",
    image: "test.jpg",
  },
];
